version: '3.6'

services:
  database:
    image: postgres:15
    volumes:
      - psql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=nextjs-kysely
      - POSTGRES_PASSWORD=postgres
  # ngrok:
  #   image: ngrok/ngrok:latest
  #   restart: unless-stopped
  #   command:
  #     - "start"
  #     - "--all"
  #     - "--config"
  #     - "/etc/ngrok.yml"
  #   volumes:
  #     - ./ngrok.yml:/etc/ngrok.yml
  #   ports:
  #     - 4040:4040
  #   environment:
  #     - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
volumes:
  psql: {}
